[server]
fileWatcherType = "poll"
headless = true
runOnSave = false
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "warning"
